### PR TITLE
WIFI-7726: Updated code to fetch temp to search more possible locations

### PR DESCRIPTION
**Pull request by shimmy568**
In it's current state this code doesn't find the temperature data for all AP types. This fix is to update the code to search for more possible locations for the temperature data. The main functionality for this code was taken from how we had this functionality working in the opensync version of the code base ([stats.c](https://github.com/Telecominfraproject/wlan-ap/blob/1ba2fcbe0a02013125d90380b5b96856b994f883/feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/stats.c#L389)).

### CODE REVIEW

**Comment by blogic** [comment]
this patch looks incorrect, it reads out the cpu temperature by the look of it.

**Comment by shimmy568** [comment]
> this patch looks incorrect, it reads out the cpu temperature by the look of it.

It shouldn't be. The first path we check for is the same path as was being used previously (temp1_input file inside /sys/class/ieee80211/phy0/device/hwmon/*) and the second path is a different path that's used on some AP models. Both paths are including the radio as a paramter (for the %s). Just based on that it should be reading radio temperature

**Comment by shimmy568** [comment]
@blogic Any particular reason the PR was closed without merging? I realize the branch name is incorrect. This fix is to fix the radio temperature code not the CPU temperature code.

But I've tested this fix on both my EX227 and EA8300 and it works for both. If there's any issue with the patch I don't mind fixing it just let me know what it is.

**Comment by blogic** [comment]
the patch reads out the tsens values, which are the thermal sensors of the cpu. if you look at your patch closely, any phy that fails to read thermal, will just use the 0th sensor of tsens.

also, in my testing ea8300 and all the qca ax units worked, as long as the phy is actually up.

**Pull request closed without merging**
